baseURL:  'http://localhost:1313/'
languageCode: 'en-gb'

enableRobotsTXT: true

params:
  title: 'hugle'
  description: "Hughie's pages of writing, Dharma, kites and magic."

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
